# Generated by Django 2.2.4 on 2020-05-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_graph_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Você', 'Você'), ('Equipe', 'Equipe'), ('Finanças', 'Finanças')], default='Você', max_length=9)),
                ('photo', models.ImageField(null=True, upload_to='photo_notification')),
                ('details', models.TextField()),
                ('date', models.DateTimeField()),
                ('iink_notification', models.CharField(blank=True, help_text='Se houver. ', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('link_youtube', models.CharField(max_length=200)),
                ('types', models.CharField(choices=[('Reunião', 'Reunião'), ('Academia', 'Academia')], default='Reunião', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='image_vote')),
                ('details', models.TextField()),
                ('Vote', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Branco', 'Branco')], default='Branco', max_length=9)),
            ],
        ),
        migrations.RenameField(
            model_name='techay_user',
            old_name='Music',
            new_name='music',
        ),
        migrations.AlterField(
            model_name='graph_site',
            name='month',
            field=models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], default='Janeiro', max_length=20),
        ),
        migrations.AlterField(
            model_name='graph_team',
            name='month',
            field=models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], default='Janeiro', max_length=20),
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('billet', models.CharField(help_text='Link do boleto.', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Client')),
            ],
        ),
    ]
