# Generated by Django 2.2.4 on 2020-05-04 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20200503_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_Techay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Máximo de 20 caracteres', max_length=20)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('techay_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Techay_User')),
            ],
        ),
        migrations.CreateModel(
            name='Token_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Máximo de 20 caracteres', max_length=20)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User_Client')),
            ],
        ),
    ]
