# Generated by Django 2.2.4 on 2020-05-04 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_client',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User_Client'),
        ),
        migrations.AlterField(
            model_name='token_techay',
            name='techay_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Techay_User'),
        ),
    ]
